# Generated by Django 3.2.6 on 2021-11-08 10:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('namear', models.CharField(max_length=200)),
                ('image', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('gains', models.TextField(blank=True, null=True)),
                ('scat_id', models.IntegerField(blank=True, null=True)),
                ('subcat_id', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('user_id', models.IntegerField(blank=True, default=0, null=True)),
                ('user_name', models.CharField(max_length=255)),
                ('type', models.IntegerField(default=0, null=True)),
                ('students_admitted', models.IntegerField(default=0)),
                ('students_passed', models.IntegerField(default=0)),
                ('header_img', models.CharField(max_length=255)),
                ('cover_img', models.CharField(max_length=255)),
                ('course_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('course_level', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3)])),
                ('dripping', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('pending', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('approval_status', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section_id', models.IntegerField(null=True)),
                ('title', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('answer', models.CharField(max_length=255)),
                ('nos', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='questions1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1024)),
                ('type', models.CharField(max_length=200)),
                ('section_id', models.IntegerField(blank=True, null=True)),
                ('aw_1_type', models.CharField(max_length=200)),
                ('aw_1_result', models.CharField(max_length=200)),
                ('aw_1_data', models.TextField(blank=True, null=True)),
                ('aw_2_type', models.CharField(max_length=200)),
                ('aw_2_result', models.CharField(max_length=200)),
                ('aw_2_data', models.TextField(blank=True, null=True)),
                ('aw_3_type', models.CharField(max_length=200)),
                ('aw_3_result', models.CharField(max_length=200)),
                ('aw_3_data', models.TextField(blank=True, null=True)),
                ('aw_4_type', models.CharField(max_length=200)),
                ('aw_4_result', models.CharField(max_length=200)),
                ('aw_4_data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('course_id', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(default='1', max_length=200)),
                ('nos', models.CharField(max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='student_mark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.IntegerField(null=True)),
                ('student_id', models.IntegerField(null=True)),
                ('mark', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='TestVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('user_id', models.IntegerField(max_length=11)),
                ('review', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fees', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('revenue', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('course_id', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoUploads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('section_id', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(max_length=200)),
                ('promo', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)])),
                ('duration', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)])),
                ('lock', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='subcategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('namear', models.CharField(max_length=200)),
                ('image', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.categories')),
            ],
        ),
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField(max_length=255)),
                ('result', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3)])),
                ('pending', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(3)])),
                ('student_id', models.IntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.courses')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.questions')),
            ],
        ),
    ]
