# Generated by Django 3.2.9 on 2021-11-21 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        
    ]
