# Generated by Django 3.2.9 on 2021-11-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20211121_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='testvideo',
            name='vimeo_url',
            field=models.CharField(default='', max_length=25),
        ),
    ]
