# Generated by Django 3.2.9 on 2021-11-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_testvideo_vimeo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='videouploads',
            name='vimeo_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='testvideo',
            name='vimeo_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
