# Generated by Django 3.2.6 on 2021-12-21 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20211207_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testvideo',
            name='review',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='testvideo',
            name='user_id',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(90)]),
        ),
    ]
