# Generated by Django 3.2.6 on 2021-10-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oname', models.CharField(default='', max_length=255)),
                ('oval', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
