# Generated by Django 3.2.6 on 2021-11-10 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(default='', max_length=1000)),
                ('course_id', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(11)])),
                ('student_id', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(11)])),
            ],
        ),
    ]
