# Generated by Django 3.2.6 on 2021-12-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='passport_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
