# Generated by Django 3.2.6 on 2021-12-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_card_passport_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='passport_number',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='bank_number',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_number',
            new_name='passport_no',
        ),
    ]
