# Generated by Django 3.2.6 on 2021-12-08 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211208_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='passport_no',
            new_name='passport_number',
        ),
    ]
