# Generated by Django 3.2.6 on 2021-12-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_passport_no_card_passport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincontrol',
            name='offer_percentage',
            field=models.IntegerField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='admincontrol',
            name='offer_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
